<?php

namespace Tests\Feature;

use Database\Seeders\TodoSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class TodolistControllerTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete("delete from todos");
    }

    public function testTodolist()
    {
        $this->seed(TodoSeeder::class);
        $this->withSession([
            "user" => "Samuel"
        ])->get('/todolist')
            ->assertSeeText("1")
            ->assertSeeText("Eko");
    }

    public function testAddTodoFailed()
    {
        $this->withSession([
            "user" => "samuel"
        ])->post("/todolist", [])
            ->assertSeeText("Todo is required");
    }

    public function testAddTodoSuccess()
    {
        $this->withSession([
            "user" => "samuel"
        ])->post("/todolist", [
            "todo" => "andrey"
        ])->assertRedirect("/todolist");
    }

    public function testRemoveTodolist()
    {
        $this->withSession([
            "user" => "samuel",
            "todolist" => [
                [
                    "id" => "1",
                    "todo" => "andrey"
                ],
                [
                    "id" => "2",
                    "todo" => "prasetya"
                ]
            ]
        ])->post("/todolist/1/delete")
            ->assertRedirect("/todolist");
    }
}
